### ISSUE TITLE
application.properties unknown property

### ISSUE THREAD

**Issue by edubois10** [RedHatTraining/AD482-apps#77]
I am doing the AD482 course, and I am not able to run correctly some of the labs. Currently I am working on the "Guided Exercise: Processing Data Streams". I notice that in the application.properties some properties are unknown, and therefore when running the application I cannot connect to the bootstrap server.

The properties are : 
kafka.security.protocol = SSL
kafka.ssl.truststore.location = /AbsolutePath/truststore.jks
kafka.ssl.truststore.password = password

I had issues with the other labs as well, but to overcome it I deployed the app in the cluster and removed these properties.

Would be great if you could have a look at this. 

Best,

Etienne.

**Comment by jramcast** [comment]
Hello, can you post the application logs where the error is shown?

**Comment by mabulgu** [comment]
Hi @edubois10. You dont have to deploy the app in the cluster. Probably you are missing some setup steps so that would be cool if you can share the detailed logs with us. 

If you want to experiment those on the cluster, removing the SSL and security stuff is not enough since you need to also change the kafka address from route to service URL, which we keep in the .env file where it should be created in the very first setup steps of the course. "lab start" command normally copies that to your application directory, so be sure to have it in your directory ~/AD482/[exercise-name]
